name: cd

on:
  push:
    branches-ignore:
      - main

jobs:
  deploy:
    if: "!contains(github.event.head_commit.message, 'skipci')"
    uses: octue/workflows/.github/workflows/deploy-cloud-run-service.yml@main
    permissions:
      id-token: write
      contents: read
    with:
      gcp_project_name: octue-twined-services
      gcp_project_number: 13074362726
      gcp_region: europe-west9
      gcp_resource_affix: octue
      gcp_service_name: turbsim-service
      local_dockerfile: ./Dockerfile
